# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3A09PzheyLFQ-2Lfju5Bfa5VeyMxCvZ
"""

!pip install transformers gradio --quiet

from transformers import GPT2Tokenizer, GPT2LMHeadModel
import torch
import gradio as gr

# Load tokenizer and model
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")
model.eval()

# Generate text function
def generate_text(prompt):
    inputs = tokenizer.encode(prompt, return_tensors="pt")
    outputs = model.generate(inputs, max_length=150, num_return_sequences=1, do_sample=True, temperature=0.7)
    decoded_output = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return decoded_output

# Gradio Interface
interface = gr.Interface(fn=generate_text, inputs="text", outputs="text", title="GPT-2 Text Generator")

# Launch with public sharable link
interface.launch(share=True)